### ISSUE TITLE
Sub Title is Not working

### ISSUE THREAD

**Issue by lalitkumarjoomdev** [hiteshaggarwal/JD-Extensions#4]
sub title frontend me show nhi ho raha or jab hum ReadMore button ko Enable karte hai tab layout kharab ho jata hai

**Comment by Sumesh577** [comment]
@lalitkumarjoomdev Subtitle start show to frontend.

**Comment by lalitkumarjoomdev** [comment]
@Sumesh577 @Priyasingh23 
Read More button lagane par pura layout kharab ho raha hai

**Comment by Sumesh577** [comment]
@lalitkumarjoomdev @Priyasingh23 
Now  done.
